### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by Aloradri** [Tomato6966/Multiguild-Modmail#1]
I hereby wated to say that this code is not working

**Comment by junny2233** [comment]
> I hereby wated to say that this code is not working

code is working is being use in the server currently. mine is working.

**Comment by Aloradri** [comment]
> > I hereby wated to say that this code is not working
> 
> code is working is being use in the server currently. mine is working.

I mean i just try to make the bot but the code not working showing erors

**Comment by junny2233** [comment]
> > > I hereby wated to say that this code is not working
> > 
> > 
> > code is working is being use in the server currently. mine is working.
> 
> I mean i just try to make the bot but the code not working showing erors

what errors? you need to provide more information so people can help you :)

**Comment by testbot-github** [comment]
> > > I hereby wated to say that this code is not working
> > 
> > 
> > code is working is being use in the server currently. mine is working.
> 
> I mean i just try to make the bot but the code not working showing erors

Show the error so we can help you :)

**Comment by Nyte-Blade** [comment]
Error: Cannot find module 'node:events'
Require stack:
- /home/runner/Multiguild-Modmail/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/Multiguild-Modmail/node_modules/discord.js/src/index.js
- /home/runner/Multiguild-Modmail/index.js

tried it in replit (IDE)

**Comment by Caallum** [comment]
You need to update the node version for your repl to 16.6 or above,

And this is how:

**Replit Node 16.6.1**

`
npm i --save-dev node@16.6.1 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH `

Put that code into the **shell** and add a `.replit` file with the code:

`
run = "npm start"`

And in your package.json file add
`
"scripts": {
  "start": "node index.js"
}`

**Comment by dg024781** [comment]
![Screenshot_20220518-114052](https://user-images.githubusercontent.com/97373574/168969445-19de8f45-fdb9-4228-add7-f3e7affe74d9.png)
Not working can any one give me working replit link or explain the process
